import Head from "next/head"
import Link from "next/link"
import {
    Men,
    Cart
  } from "./icons";

export default function Log({ children, title }){
    return(
        <div className="flex flex-col items-center justify-center min-h-screen py-2 hero">
            <Head>
        <title>Nutriña | Inicio de sesión{title ? `| ${title}` : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">{children}
            <div className="bg-white rounded-2xl shadow-2xl flex w-2/3 max-w-4xl">
            <div className="w-3/5 p-5">
                <div className="text-left font-bold">
                    <span className="text-green-300">Nutriña</span>
                </div>
                <div className="py-10">
                    <h2 className="text-3xl font-bold text-cyan-400 mb-2">Iniciar Sesión</h2>
                    
                </div>
                <div className="flex justify-center my-2">
                    <div className="flex flex-col items-center mb-3">
                        <div className="bg-gray-100 w-64 p-2 flex items-center">
                            <Cart className="text-gray-400 m-2"/>
                            <input
                            type="email"
                            name="email"
                            placeholder="Correo electronico"
                            className="bg-gray-100 outline-none text-sm" ></input>
                        </div>
                    </div>
                </div>
                <div className="flex flex-col items-center mb-3">
                        <div className="bg-gray-100 w-64 p-2 flex items-center">
                            <Men className="m-2"/>
                            <input
                            type="password"
                            name="password"
                            placeholder="Contraseña"
                            className="bg-gray-100 outline-none text-sm" ></input>
                        </div>
                    </div>
                    <div className="mb-3">
                    <a className="border-2 border-green-500 text-green-500 rounded-full px-12 py-2 inline-block font-semibold 
                    hover:bg-white hover:text-green-500">Iniciar Sesión</a></div>
                    <a className="border-2 border-green-500 text-green-500 rounded-full px-12 py-2 inline-block font-semibold 
                    hover:bg-white hover:text-green-500">Regresar</a>
                </div>
            {/** sign in section */}
            <div className="w-2/5 rounded-tr-2xl rounded-br-2xl ">
            <img src="cd.jpg"  className="rounded-tr-2xl rounded-br-2xl"></img>
                </div>
            {/**sign up section */}
            </div>
            </main>
        </div>
    )
}